[workspace]
members = ["core", "debug", "rapier"]

[package]
name = "heron"
version = "0.5.1"
authors = ["Jonathan Cornaz"]
edition = "2018"
license = "MIT"
description = "An ergonomic physics API for 2d and 3d bevy games. (powered by rapier)"
repository = "https://github.com/jcornaz/heron/"
keywords = ["game", "gamedev", "physics", "collision", "bevy"]
categories = ["game-development", "simulation"]
build = "build.rs"

[features]
default = ["3d"]
2d = ["heron_rapier/2d", "heron_debug/2d"]
3d = ["heron_rapier/3d", "heron_debug/3d"]
debug = ["heron_debug"]

[build-dependencies]
skeptic = "0.13"

[dependencies]
heron_core = { path = "core", version = "^0.5.0"}
heron_rapier = { path = "rapier", version = "^0.5.0"}
heron_debug = { path = "debug", version = "^0.5.0", optional = true }
bevy = { git = "https://github.com/bevyengine/bevy.git", rev = "7d0e98f34c43eb62522c0c65de64f7b458b899be", default-features = false }

[dev-dependencies]
skeptic = "0.13"

[[example]]
name = "demo"
required-features = ["2d"]

[[example]]
name = "debug"
required-features = ["2d", "debug"]

[[package.metadata.release.pre-release-replacements]]
file = "CHANGELOG.md"
search = "## \\[Unreleased\\]"
replace = "## [Unreleased]\n\n\n\n## [{{version}}] - {{date}}"
exactly = 1
prerelease = true

[[package.metadata.release.pre-release-replacements]]
file = "CHANGELOG.md"
search = "\\.\\.\\.HEAD"
replace = "...v{{version}}"
exactly = 1
prerelease = true

[[package.metadata.release.pre-release-replacements]]
file = "CHANGELOG.md"
search = "\\[Unreleased\\]: "
replace = "[Unreleased]: ../../compare/v{{version}}...HEAD\n[{{version}}]: "
exactly = 1
prerelease = true

[[package.metadata.release.pre-release-replacements]]
file = "src/lib.rs"
search = "//! heron = \".+\""
replace = "//! heron = \"{{version}}\""
prerelease = true

[[package.metadata.release.pre-release-replacements]]
file = "src/lib.rs"
search = "//! heron = \\{ version = \"[0-9a-z\\.-]+\""
replace = "//! heron = { version = \"{{version}}\""
prerelease = true

[[package.metadata.release.pre-release-replacements]]
file = "README.md"
search = "heron = \".*\""
replace = "heron = \"{{version}}\""
prerelease = true

[[package.metadata.release.pre-release-replacements]]
file = "README.md"
search = "heron = \\{ version = \"[0-9a-z\\.-]+\""
replace = "heron = { version = \"{{version}}\""
prerelease = true

[[package.metadata.release.pre-release-replacements]]
file = "guide/src/quickstart.md"
search = "heron = \\{ version = \"[0-9a-z\\.-]+\""
replace = "heron = { version = \"{{version}}\""
prerelease = true
